apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: feupzm4f491j4c
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
