plugins {
    id "java"
    id "maven-publish"
    id "com.github.davidmc24.gradle.plugin.avro" version "$avroPluginVersion"
}

group = "org.ourcode"
version = "$appVersion"
description = "avro-schemas"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

dependencies {
    implementation "org.apache.avro:avro:${avroVersion}"
}

repositories {
    mavenCentral()
}

avro {
    createSetters = true
    fieldVisibility = 'PRIVATE'
}

publishing {

    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group.toString()
            artifactId = project.name.toString()
            version = project.version.toString()
        }
    }

    repositories {
        maven {
            name = "localNexus"
            allowInsecureProtocol = true

            def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
            url = uri("http://${nexusHost}/repository/iot-libs-release-local")

            credentials {
                username = findProperty("nexus_user") ?: "admin"
                password = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"
            }
        }
    }

}