plugins {
    id "java"
    id "maven-publish"
    id "com.github.davidmc24.gradle.plugin.avro" version "$avroPluginVersion"
}

group = "org.ourcode"
version = "$appVersion"
description = "avro-schemas"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

dependencies {
    implementation "org.apache.avro:avro:${avroVersion}"
}

repositories {
    mavenCentral()
}

avro {
    createSetters = true
    fieldVisibility = 'PRIVATE'
}

publishing {

    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group.toString()
            artifactId = project.name.toString()
            version = project.version.toString()
        }
    }

    repositories {
        maven {
            name = "localNexus"
            allowInsecureProtocol = true

            def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
            url = uri("http://${nexusHost}/repository/iot-libs-release-local")

            credentials {
                username = findProperty("nexus_user") ?: "admin"
                password = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"
            }
        }
    }

}

String artifactUrl() {
    def groupName = project.group.toString().replace('.', '/')
    def version = project.version
    def name = project.name

    def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
    return "http://${nexusHost}/repository/iot-libs-release-local/" +
            "${groupName}/${name}/${version}/${name}-${version}.jar"
}

String authHeader() {
    def nexusUser = findProperty("nexus_user") ?: "admin"
    def nexusPassword = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"

    def auth = "${nexusUser}:${nexusPassword}".bytes.encodeBase64().toString()
    return "Basic ${auth}"
}

boolean artifactAlreadyPublished() {
    def artifactUrl = artifactUrl()
    println "Checking if artifact exists at: ${artifactUrl}"

    def connection = new URI(artifactUrl).toURL().openConnection()
    connection.setRequestMethod("HEAD")
    connection.setRequestProperty("Authorization", authHeader())
    connection.connect()

    if (connection.responseCode == 200) {
        println "Artifact ${group}:${name}:${version} already exists in Nexus"
        println "Skipping publish - artifact already exists"

        return true
    } else {
        println "Response code: ${connection.responseCode}"
        println "Artifact ${group}:${name}:${version} does not exist in Nexus, or cannot be accessed"
        println "Proceeding with publish"

        return false
    }
}

tasks.withType(PublishToMavenRepository).configureEach {
    onlyIf {
        !artifactAlreadyPublished()
    }
}