spring:
  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: false
    consumer:
      auto-offset-reset: latest
      group-id: event-collector-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 100
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        max.poll.interval.ms: 300000
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000