global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka_exporter:9308' ]
    scrape_interval: 10s
    metrics_path: /metrics