plugins {
    id "java"
    id "java-library"
    id "maven-publish"
    id "org.openapi.generator" version "$openApiGeneratorVersion"
}

group = "org.ourcode"
version = "$appVersion"
description = "rest-clients"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

dependencies {
    api "io.swagger.core.v3:swagger-annotations:${swaggerVersion}"
    api "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    api "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
}

repositories {
    mavenCentral()
}

openApiGenerate {
    generatorName.set("spring")
    inputSpec.set(file("src/main/resources/interface/device-service.yaml").toURI().toString())

    modelPackage.set("org.ourcode.rest.model")
    apiPackage.set("org.ourcode.rest.api")

    generateApiDocumentation.set(false)
    generateApiTests.set(false)
    generateModelDocumentation.set(false)
    generateModelTests.set(false)

    configOptions.set([
            basePackage            : "org.ourcode.generated",
            interfaceOnly          : "true",
            dateLibrary            : "java8",
            openApiNullable        : "false",
            serializableModel      : "true",
            library                : "spring-boot",
            useBeanValidation      : "true",
            useJakartaEe           : "true",
            useTags                : "true",
    ])
}

sourceSets.main.java.srcDir "${layout.buildDirectory.get()}/generate-resources/main/src/main/java"

compileJava.dependsOn tasks.openApiGenerate

tasks.withType(JavaCompile).configureEach {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs += ['-parameters']
}

publishing {

    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group.toString()
            artifactId = project.name.toString()
            version = project.version.toString()
        }
    }

    repositories {
        maven {
            name = "localNexus"
            allowInsecureProtocol = true

            def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
            url = uri("http://${nexusHost}/repository/iot-libs-release-local")

            credentials {
                username = findProperty("nexus_user") ?: "admin"
                password = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"
            }
        }
    }

}

String artifactUrl() {
    def groupName = project.group.toString().replace('.', '/')
    def version = project.version
    def name = project.name

    def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
    return "http://${nexusHost}/repository/iot-libs-release-local/" +
            "${groupName}/${name}/${version}/${name}-${version}.jar"
}

String authHeader() {
    def nexusUser = findProperty("nexus_user") ?: "admin"
    def nexusPassword = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"

    def auth = "${nexusUser}:${nexusPassword}".bytes.encodeBase64().toString()
    return "Basic ${auth}"
}

boolean artifactAlreadyPublished() {
    def artifactUrl = artifactUrl()
    println "Checking if artifact exists at: ${artifactUrl}"

    def connection = new URI(artifactUrl).toURL().openConnection()
    connection.setRequestMethod("HEAD")
    connection.setRequestProperty("Authorization", authHeader())
    connection.connect()

    if (connection.responseCode == 200) {
        println "Artifact ${group}:${name}:${version} already exists in Nexus"
        println "Skipping publish - artifact already exists"

        return true
    } else {
        println "Response code: ${connection.responseCode}"
        println "Artifact ${group}:${name}:${version} does not exist in Nexus, or cannot be accessed"
        println "Proceeding with publish"

        return false
    }
}

tasks.withType(PublishToMavenRepository).configureEach {
    onlyIf {
        !artifactAlreadyPublished()
    }
}