plugins {
    id "java"
    id "java-library"
    id "maven-publish"
    id "org.openapi.generator" version "$openApiGeneratorVersion"
}

group = "org.ourcode"
version = "$appVersion"
description = "rest-clients"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

dependencies {
    api "io.swagger.core.v3:swagger-annotations:${swaggerVersion}"
    api "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    api "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"
}

repositories {
    mavenCentral()
}

openApiGenerate {
    generatorName.set("spring")
    inputSpec.set(file("src/main/resources/interface/device-service.yaml").toURI().toString())

    modelPackage.set("org.ourcode.rest.model")
    apiPackage.set("org.ourcode.rest.api")

    generateApiDocumentation.set(false)
    generateApiTests.set(false)
    generateModelDocumentation.set(false)
    generateModelTests.set(false)

    configOptions.set([
            basePackage            : "org.ourcode.generated",
            interfaceOnly          : "true",
            dateLibrary            : "java8",
            openApiNullable        : "false",
            serializableModel      : "true",
            library                : "spring-boot",
            useBeanValidation      : "true",
            useJakartaEe           : "true",
            useTags                : "true",
    ])
}

sourceSets.main.java.srcDir "${layout.buildDirectory.get()}/generate-resources/main/src/main/java"

compileJava.dependsOn tasks.openApiGenerate

tasks.withType(JavaCompile).configureEach {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs += ['-parameters']
}

publishing {

    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group.toString()
            artifactId = project.name.toString()
            version = project.version.toString()
        }
    }

    repositories {
        maven {
            name = "localNexus"
            allowInsecureProtocol = true

            def nexusHost = findProperty("nexus_host") ?: "localhost:8081"
            url = uri("http://${nexusHost}/repository/iot-libs-release-local")

            credentials {
                username = findProperty("nexus_user") ?: "admin"
                password = findProperty("nexus_password") ?: "fdfaec4c-c569-4835-a0cd-d51e5d4500e9"
            }
        }
    }

}