{
 "title": "Device Collector",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Device processing errors",
   "type": "barchart",
   "description": "If device can't be processed (for example, values can't inserted to the db) the metric is incremented",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "devicecollector_devices_errors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device invalid errors",
   "type": "barchart",
   "description": "If message can't be deserialized the metric is incremented",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "devicecollector_devices_invalid_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of successfully processed devices",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "devicecollector_devices_successful_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}