server:
  port: 8090

spring:
  application:
    name: device-service
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:db/sharding.yaml?placeholder-type=environment
  flyway:
    enabled: false
  retry:
    device-gateway:
      max-attempts: 3
      backoff-delay: 500

flyway:
  locations: classpath:db/migrations
  dataSources:
    - name: shard_0
      url: ${SHARD_0_JDBC_URL:jdbc:postgresql://localhost:5433/our_code_db}
      username: ${SHARD_0_USER:our_code_user}
      password: ${SHARD_0_PASSWORD:our_code_password}
    - name: shard_1
      url: ${SHARD_1_JDBC_URL:jdbc:postgresql://localhost:5434/our_code_db}
      username: ${SHARD_1_USER:our_code_user}
      password: ${SHARD_1_PASSWORD:our_code_password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, ping
        readiness:
          include: readinessState, shard